version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-couchbase}
      - DB_PORT=${DB_PORT:-11210}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
      - DB_BUCKET=${DB_BUCKET:-online-booking}
    depends_on:
      - couchbase
    networks:
      - booking-network
    restart: unless-stopped

networks:
  booking-network:
    driver: bridge